name: crossover_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  get: ^4.6.4
  dio: ^4.0.6
  logger: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  dio_logger: ^4.0.8+8
  flutter_screenutil: ^5.8.1
  infinite_scroll_pagination: ^3.2.0
  detectable_text_field: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_sprite: ^3.0.4
  flutter_launcher_icons: ^0.13.0

flutter_launcher_icons:
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
# flutter_launcer_icons configuration (https://pub.dev/packages/flutter_launcher_icons)
# flutter_icons:
#   android: true
#   image_path: "assets/images/Common/NOUNS_Icon.png"
#   ios:
#     generate: true
#     remove_ios_alpha: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Light.ttf
          weight: 300
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Semibold.ttf
          weight: 600
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/FontsFree-Net-SF-Pro-Rounded-Heavy.ttf
          weight: 800
